### PR TITLE
renderonly driver for exynos

### PR DESCRIPTION
**Pull request by fourkbomb**
This code is based off the sun4i-drm renderonly driver by
@enunes.

kmscube verified to work on exynos4412 with MIPI-DSI LCD.

### CODE REVIEW

**Comment by enunes** [comment]
I did a quick review comparing this patch and the sun4i one, and it looks reasonable for me.
Apparently the common parts did not require modification, in the lima_resource or winsys, the rest seems to be a copy+rename for exynos which looks fine to me.
The copyright notices kept 2017 instead of 2018 but not sure if it matters too much.

I don't have an exynos board, I build-tested this with cross-compilation using buildroot-external-lima and it seems fine, so I can include the exynos build in buildroot-external-lima too after this is merged.

**Comment by fourkbomb** [comment]
Thanks for the review!

I think the only difference between exynos and sunxi would be that exynos can display non-contiguous buffers (as far as i can see sunxi doesn't have IOMMUs for display output?), but since lima doesn't support those yet, there's nothing different.

I left 2017 in the copyright because it's so similar to your code. I can change it to 2018 if it matters.

**Comment by yuq** [comment]
It looks good for me too, thanks.

Does exynos display drm driver support non-contiguous mem by IOMMU or the display engine HW?

**Comment by fourkbomb** [comment]
exynos drm uses an IOMMU

**Comment by yuq** [comment]
OK, I think we can pass an option to lima_screen_create in the future to indicate if display support non-contiguous mem after lima support this too.

**Pull request merged**
